POOL-1262 Components library, useAppEnv, match flagship for localization
pooltogether/pooltogether-governance-ui pull request #51
Opened 2021-05-31 16:47 UTC by ddesrosier

- Integrate v.0.0.1 of the components library, just using it for tailwind config & css for now.
- Update the app to use `useAppEnv` to get the proper network for users. Now the app handles when a users wallet is on an unsupported network
- Update localization code to match flagship

2021-05-31 20:04 UTC, chuckbergeron commented on lib/components/TransactionsList.jsx
> -    if ((usersAddress, chainId)) {
that's... weird

2021-05-31 20:06 UTC, chuckbergeron requested changes
The Settings menu has "Use testnets" as an option, and that seems to be the switch to change the content from ETH Mainnet to Rinkeby. However I can still be connected to the wrong network and get the other network's content (ie I'm on Mainnet with my wallet and see Rinkeby proposals). We should prob have the same two different arrays as the flagship, and have [Networks.mainnet] in the production one and [Networks.rinkeby] in the testnets one, instead of relying on the 1 `SUPPORTED_CHAIN_IDS` in the constants file.

Also let's make sure you can't create a tx for the wrong network! I see you have `disabled` on the buttons, but in the flagship we also show a tooltip saying you need to change you wallet network. Can prob just copy and paste that code.

The one other thing I noticed is how different the layouts are between the flagship and the vote app now, and how the ETH diamond image doesn't show up in the header but instead it says 'E'.

2021-06-15 14:53 UTC, ddesrosier commented
There's a ton of changes now. Majority of components have been migrated, most importantly is the layout, navigation & header. Some specific things to look at:
- layout, navigation & header
- account / pending transactions modal & trigger updates
    - Moved to a single `Modal` component
    - `1 pending` replaces the users address/icon rather than being placed beside
        - I copied Uniswap for this. Mostly so the header isn't shifting around when we send a transaction
- network selection modal
    - https://github.com/pooltogether/pooltogether-react-components/tree/main/lib/components/PageHeader/NetworkSelector 
    - modals are just quicker so I didn't add the dropdown like the designs. I can update that before we release anything
    - There's different content for when Metamask is connected vs another wallet

I've created a proposal , voted & queued on Rinkeby so everything seems to be functioning fine.

Pending tx / account modal
<img width="795" alt="Screen Shot 2021-06-15 at 9 46 54 AM" src="https://user-images.githubusercontent.com/13701258/122073540-7c720d00-cdc6-11eb-9143-3441582690c4.png">

Page header
<img width="1084" alt="Screen Shot 2021-06-15 at 9 46 42 AM" src="https://user-images.githubusercontent.com/13701258/122073553-7ed46700-cdc6-11eb-91fc-604e0881fe0e.png">
<img width="439" alt="Screen Shot 2021-06-15 at 9 46 01 AM" src="https://user-images.githubusercontent.com/13701258/122073697-9f042600-cdc6-11eb-9170-b67a056e9fdf.png">

Network selection modal (with Metamask connected)
<img width="510" alt="Screen Shot 2021-06-15 at 9 46 31 AM" src="https://user-images.githubusercontent.com/13701258/122073565-8136c100-cdc6-11eb-8303-406975b41270.png">
<img width="417" alt="Screen Shot 2021-06-15 at 9 46 23 AM" src="https://user-images.githubusercontent.com/13701258/122073579-8431b180-cdc6-11eb-848c-6dddafb0d130.png">

Network selection modal (with non-metamask connected)
<img width="417" alt="Screen Shot 2021-06-15 at 10 52 44 AM" src="https://user-images.githubusercontent.com/13701258/122075146-d6270700-cdc7-11eb-87b6-f43c3cb532ac.png">

Settings popout
<img width="412" alt="Screen Shot 2021-06-15 at 9 46 07 AM" src="https://user-images.githubusercontent.com/13701258/122073606-8b58bf80-cdc6-11eb-85d3-dee3c8896f22.png">

2021-06-16 02:37 UTC, chuckbergeron commented
The screenshots are looking good! One thing, could we move that tooltip 'i' beside the Ethereum button on the network modal when Ethereum is connected? It doesn't look correct having the buttons two different widths.

One thing we could do is wrap it so it looks like one button.

```
|-----------------------|
| Ethereum              |   i   |
|-----------------------|
```

2021-06-16 02:41 UTC, chuckbergeron commented
Getting a few errors in the console:

<img width="596" alt="Screenshot 2021-06-15 at 19 41 01" src="https://user-images.githubusercontent.com/35717/122149873-9edd4800-ce11-11eb-9c78-003a6fe040c8.png">


<img width="617" alt="Screenshot 2021-06-15 at 19 41 11" src="https://user-images.githubusercontent.com/35717/122149890-a4d32900-ce11-11eb-8205-6b0ae1d0fda3.png">

2021-06-16 02:44 UTC, chuckbergeron commented
Could we swap these so they go from this gray color to green? I find links typically go from whatever state they are to something brighter on hover, so this dropping of opacity on hover feels wrong to me:

<img width="389" alt="Screenshot 2021-06-15 at 19 44 24" src="https://user-images.githubusercontent.com/35717/122150175-17440900-ce12-11eb-85cf-64447c03a895.png">

2021-06-16 02:45 UTC, chuckbergeron commented
Same thing for buttons, the hover state looks disabled?

<img width="510" alt="Screenshot 2021-06-15 at 19 44 50" src="https://user-images.githubusercontent.com/35717/122150221-27f47f00-ce12-11eb-8af8-ded8680a2d75.png">

2021-06-16 02:45 UTC, chuckbergeron commented
It's in the nav, too:
<img width="243" alt="Screenshot 2021-06-15 at 19 45 20" src="https://user-images.githubusercontent.com/35717/122150267-393d8b80-ce12-11eb-83ad-40c0c5129979.png">
😂

2021-06-16 02:47 UTC, chuckbergeron commented
This could use at least double the padding:
<img width="491" alt="Screenshot 2021-06-15 at 19 47 05" src="https://user-images.githubusercontent.com/35717/122150386-77d34600-ce12-11eb-9353-1fdf6ee0c174.png">


For reference here's what the design looks like in Figma:
<img width="786" alt="Screenshot 2021-06-15 at 19 47 30" src="https://user-images.githubusercontent.com/35717/122150407-86216200-ce12-11eb-89aa-2ba179ecfd5a.png">

2021-06-23 14:54 UTC, merged